### ISSUE TITLE
Start mining failed with error----datastore: key not found

### ISSUE THREAD

**Issue by maobisheng** [filecoin-project/lotus#400]
root@ipfsunion:~/lotus# lotus-storage-miner run
2019-10-17T11:03:09.783Z        INFO    badger  badger@v1.6.0-rc1/logger.go:46  All 0 tables opened in 0s

2019-10-17T11:03:09.784Z        INFO    badger  badger@v1.6.0-rc1/logger.go:46  Replaying file id: 0 at offset: 0

2019-10-17T11:03:09.784Z        INFO    badger  badger@v1.6.0-rc1/logger.go:46  Replay took: 27.143¬µs

2019-10-17T11:03:09.785Z        INFO    p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip6/::1/tcp/38443 /ip4/127.0.0.1/tcp/39523 /ip4/119.147.149.138/tcp/39523]
2019-10-17T11:03:09.786Z        WARN    main    lotus-storage-miner/main.go:71  could not build arguments for function "github.com/filecoin-project/go-lotus/node/modules".HandleDeals (/root/lotus/node/modules/storageminer.go:101): failed to build *deals.Handler: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorblocks.SectorBlocks: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sector.Store: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorbuilder.SectorBuilder: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorbuilder.SectorBuilderConfig: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: datastore: key not found

**Comment by maobisheng** [comment]
Full log as below, it seems my wallet has not enough funds: 500000000 < 18164227796594613493. how to reduce the pledge-collateral?

root@ipfsunion:~# lotus wallet balance t3q2xfgrm3ag53gjxmuvepuo3j2rc6mq4rbloenpwznyndumb5jssq2mrvttsvfvglv7ihfeu7nssba4tpl24q
500000000
root@ipfsunion:~# lotus state pledge-collateral
17545376633967355876
root@ipfsunion:~# lotus-storage-miner init --owner=t3q2xfgrm3ag53gjxmuvepuo3j2rc6mq4rbloenpwznyndumb5jssq2mrvttsvfvglv7ihfeu7nssba4tpl24q
2019-10-17T09:07:33.738Z        INFO    main    lotus-storage-miner/init.go:52  Initializing lotus storage miner
2019-10-17T09:07:33.738Z        INFO    main    lotus-storage-miner/init.go:54  Checking proof parameters
2019-10-17T09:07:33.740Z        WARN    build   build/paramfetch.go:74  Checksum mismatch in param file v12-proof-of-spacetime-rational-535d1050e3adca2a0dfe6c3c0c4fa12097c9a7835fb969042f82a507b13310e0.params, 4ea4a55719c450b00aef5b995961e6d5 != 3d245479d9b5fc668d58c493da5f3ee1
2019-10-17T09:07:33.740Z        INFO    build   build/paramfetch.go:81  Fetching /var/tmp/filecoin-proof-parameters/v12-proof-of-spacetime-rational-535d1050e3adca2a0dfe6c3c0c4fa12097c9a7835fb969042f82a507b13310e0.params
 329.55 MiB / 329.55 MiB [=============================================================================================================================================] 100.00% 66.41 KiB/s 1h24m41s
2019-10-17T10:32:15.351Z        INFO    build   build/paramfetch.go:81  Fetching /var/tmp/filecoin-proof-parameters/v12-zigzag-proof-of-replication-6496c180c2eab89ee0638bc73879ced01daf512486eb38b9e1c9402ba578e010.params
 1.41 GiB / 1.41 GiB [=====================================================================================================================================================] 100.00% 1.71 MiB/s 14m3s
2019-10-17T10:46:19.307Z        INFO    main    lotus-storage-miner/init.go:59  Checking if repo exists
2019-10-17T10:46:19.307Z        INFO    main    lotus-storage-miner/init.go:74  Trying to connect to full node RPC
2019-10-17T10:46:19.309Z        INFO    main    lotus-storage-miner/init.go:83  Checking full node version
2019-10-17T10:46:19.310Z        INFO    main    lotus-storage-miner/init.go:94  Initializing repo
2019-10-17T10:46:19.310Z        INFO    repo    repo/fsrepo.go:77       Initializing repo at '/root/.lotusstorage'
2019-10-17T10:46:19.310Z        INFO    main    lotus-storage-miner/init.go:106 Initializing libp2p identity
2019-10-17T10:46:19.311Z        INFO    main    lotus-storage-miner/init.go:249 Creating StorageMarket.CreateStorageMiner message
2019-10-17T10:46:19.315Z        WARN    main    lotus-storage-miner/main.go:71  mpool push: not enough funds: 500000000 < 18164227796594613493
root@ipfsunion:~# lotus-storage-miner run
2019-10-17T11:02:19.475Z        INFO    badger  badger@v1.6.0-rc1/logger.go:46  All 0 tables opened in 0s

2019-10-17T11:02:19.478Z        INFO    p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip4/127.0.0.1/tcp/38117 /ip4/119.147.149.138/tcp/38117 /ip6/::1/tcp/33397]
2019-10-17T11:02:19.480Z        WARN    main    lotus-storage-miner/main.go:71  could not build arguments for function "github.com/filecoin-project/go-lotus/node/modules".HandleDeals (/root/lotus/node/modules/storageminer.go:101): failed to build *deals.Handler: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorblocks.SectorBlocks: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sector.Store: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorbuilder.SectorBuilder: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorbuilder.SectorBuilderConfig: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: datastore: key not found

**Comment by whyrusleeping** [comment]
@maobisheng ah, thats a pretty ugly failure case for not having enough funds. We should make sure that `run` fails with a nice error unless `init` fully succeeded.

As for getting enough funds, i'm sending a bunch to you now (address: t3q2xfgrm3ag53gjxmuvepuo3j2rc6mq4rbloenpwznyndumb5jssq2mrvttsvfvglv7ihfeu7nssba4tpl24q) the faucet will be improved soon, but its not quite good enough yet

**Comment by Dengminer** [comment]
Hello @whyrusleeping , I have the same problem. Unable to initialize miner due to insufficient balance. Can you help me?

**Comment by Yst-find-me** [comment]
Hello,@whyrusleeping,I have the same problem as below,my balance is not enough.My address is t3qd2tqb5gj3453dngjhlyhnloqhcoij6prgv7cj6do5itpjmamgcdmej4lyo76x5gwu4yhy63rjhrz5iqivpa。please help me。 thank you。

**Comment by IPFS-grandhelmsman** [comment]
I need some, too. thanks @whyrusleeping 
t3ubcatj7dc4uzqkyeqllnzn2fduqh6i34vaw3zvh6ppuishbjobmb4znzvpjay2x4h2kgxdeqrqmaeokbdjeq

**Comment by whyrusleeping** [comment]
@Dengminer @Yst-find-me @IPFS-grandhelmsman I sent each of you funds, in the future try using the faucet to create a new miner. It has been updated and i tried it myself just now.

**Comment by Dengminer** [comment]
@whyrusleeping Thanks.

**Comment by Kubuxu** [comment]
Fixed in #412

**Comment by IPFS-grandhelmsman** [comment]
@whyrusleeping 
I compiled the latest version, and wrote a shell to get funds from faucet every 600 seconds, but it is not enough to create the second storage。
![image](https://user-images.githubusercontent.com/53922818/67084646-ef7d4780-f1cf-11e9-915d-7d7c3511938b.png)
![image](https://user-images.githubusercontent.com/53922818/67084888-6f0b1680-f1d0-11e9-8d6d-299cc01ffb78.png)

And i have created a new one to get funds from faucet, but the balance is 500000000 too.
![image](https://user-images.githubusercontent.com/53922818/67085939-5a2f8280-f1d2-11e9-8b5c-23ed0e855002.png)

![image](https://user-images.githubusercontent.com/53922818/67085855-33714c00-f1d2-11e9-9578-99df11bf3b68.png)

**Comment by Kubuxu** [comment]
@IPFS-grandhelmsman use: https://lotus-faucet.kittyhawk.wtf/miner.html

**Comment by IPFS-grandhelmsman** [comment]
@Kubuxu 

I used  https://lotus-faucet.kittyhawk.wtf/miner.html to create a new miner, but an error of `lotus/main.go:67  routing: not found` occurred when i do `lotus client deal` or `lotus client query-ask`.

And i used https://lotus-faucet.kittyhawk.wtf/funds.html to get funds, but It's still not enough funds to create a local miner.
![image](https://user-images.githubusercontent.com/53922818/67256334-0fa35400-f4b9-11e9-9731-33296535f2d7.png)

Is everyone else fixed?   i had one storage-miner for research,  but i need 2 or 3 storge-miner to make a performance testing，now it can't go on,  could you send me more funds?

My wallet address:
t3ubcatj7dc4uzqkyeqllnzn2fduqh6i34vaw3zvh6ppuishbjobmb4znzvpjay2x4h2kgxdeqrqmaeokbdjeq

thank you!

**Comment by IPFS-grandhelmsman** [comment]
> @Kubuxu
> 
> I used https://lotus-faucet.kittyhawk.wtf/miner.html to create a new miner, but an error of `lotus/main.go:67 routing: not found` occurred when i do `lotus client deal` or `lotus client query-ask`.
> 
> And i used https://lotus-faucet.kittyhawk.wtf/funds.html to get funds, but It's still not enough funds to create a local miner.
> ![image](https://user-images.githubusercontent.com/53922818/67256334-0fa35400-f4b9-11e9-9731-33296535f2d7.png)
> 
> Is everyone else fixed? i had one storage-miner for research, but i need 2 or 3 storge-miner to make a performance testing，now it can't go on, could you send me more funds?
> 
> My wallet address:
> t3ubcatj7dc4uzqkyeqllnzn2fduqh6i34vaw3zvh6ppuishbjobmb4znzvpjay2x4h2kgxdeqrqmaeokbdjeq
> 
> thank you!

I knew it, it need  `lotus-storage-miner store-garbage` to proof once, after do this, `lotus client query-ask t...` works.

**Comment by linmuqin** [comment]
Hello! I have Clean up after failed storage miner init and using the faucet to create a new miner,but It's still not enough cash,Can you help me?t3vyhbbk5wy75mgo4tg3ufgu2qfl255qy3eon6h7eldht6svggb2rln2xfe2h44uzu2aqjm6heworvdc4ey4ha@whyrusleeping thanks.

**Comment by josephzhao** [comment]
Hello
 lotus wallet list   is empty,  I have address t3uvkzigjstia52f4ivdwipdzrtdfbgolhm6rmwejwdydpmcizi5g3ect6vrunzudjz6in4qmqjipmx7p236pq
how can I set the address as wallet ?

Thanks
