### ISSUE TITLE
lotus-miner init ERROR: sync wait: handler: websocket connection closed

### ISSUE THREAD

**Issue by darkrain** [filecoin-project/lotus#5674]
Hello!
I run lotus-miner init and at the end I get this:

     Worker: 0; Base: 0; Target: 526540 (diff: 526540)
     State: persisting headers; Current Epoch: 526540; Todo: 0
     Validated 0 messages (0 per second)
     2021-02-23T21:04:48.733+0300    WARN    rpc     go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/websocket.go:678        failed to write close message: write tcp 127.0.0.1:43530->127.0.0.1:1234: write: broken pipe
     ERROR: sync wait: handler: websocket connection closed

What i should to do?
i found similar issue - https://github.com/filecoin-project/lotus/issues/4983
Developers fix it, but i still have a problem.

**Comment by magik6k** [comment]
This was fixed in v1.5.0, are you running that version?

**Comment by darkrain** [comment]
I make build from master branch couple days ago. 

`git log -1
commit f2578a8e83627904196a09bb501812f1d196f390 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4f6700a4e d1843ecca
Author: Łukasz Magiera <magik6k@users.noreply.github.com>
Date:   Fri Feb 19 12:10:18 2021 +0100

    Merge pull request #5615 from filecoin-project/feat/disputer-logs
    
    Disputer logs to its own logger
`

**Comment by darkrain** [comment]
I see you released this version yesterday, i will try update now

**Comment by darkrain** [comment]
I update all, but still have problem(

     lotus-miner version
     Daemon:  1.5.0+mainnet+git.55b85f314+api1.1.0
     Local: lotus-miner version 1.5.0+mainnet+git.55b85f314

**Comment by a578815377** [comment]
@magik6k  still have problem 
ERROR: handler: websocket connection closed

**Comment by manageryzy** [comment]
still have this problem 
v1.6.0

**Comment by EmilyCaoHong** [comment]
yes, I meet it,but how to resolve it

**Comment by EmilyCaoHong** [comment]
![image](https://user-images.githubusercontent.com/43725403/114310412-48a40e00-9b1d-11eb-859d-81cb54697fa6.png)
This problem caused my node to be inoperable

**Comment by rjan90** [comment]
I think this issue has been fixed on newer versions of Lotus, and can probably be closed! #rengjøring
