### ISSUE TITLE
Deals stay in StorageDealStaged untill sealing queue becomes empty. 

### ISSUE THREAD

**Issue by j1v** [filecoin-project/lotus#7258]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version
Daemon:  1.11.1-rc3+mainnet+git.56c35ff1e.dirty+api1.2.0
Local: lotus-miner version 1.11.1-rc3+mainnet+git.56c35ff1e.dirty
```

### Describe the Bug

Deals stay in state `StorageDealStaged` and are never packed in a sector, as long as there are sectors in the sealing queue. 

```
root@filecoin:~# lotus-miner storage-deals list | grep -i staged
...leugoxhu  2370884  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  512MiB  0 FIL                     1494720
...ttjcvh7u  2372403  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  16GiB   0 FIL                     1494720
...awmrayyu  2372402  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  512MiB  0 FIL                     1494720
...6yb633ca  2373448  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  512MiB  0 FIL                     1494720
...y3whp63a  2373660  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  512MiB  0 FIL                     1494720
...oelbbfmi  2377995  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  1GiB    0 FIL                     1494720
...wuork47m  2377996  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  256MiB  0 FIL                     1494720
...2k7qq6he  2377997  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  512MiB  0 FIL                     1494720
...greikxca  2378025  StorageDealStaged                        f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a  1GiB    0 FIL                     1494720
```

If i stop pledging new sectors and wait for the queue to get empty , lotus-miner  starts an `AP` sealing job and packs them automatically. 

This is being reproduced a lot of times in the last month and also confirmed by other users in Slack 

I have watched all logs carefully and never saw something suspicious on that subject. Also I think we have observed previously this working as I think is correct - AP as soon as there are free resources. 

### Logging Information

```text
none
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Shekelme** [comment]
I'd say it only occures whet there are CC sectors in sealing pipeline. I can confirm this problem, `lotus version 1.11.1+mainnet+git.15d90c24e`

**Comment by jennijuju** [comment]
what's your MaxSealingSectorsForDeals in miner configuration

**Comment by j1v** [comment]
It was low. I have increased it after finding this [issue](https://github.com/filecoin-project/lotus/issues/3482) and now waiting for results.

**Comment by Shekelme** [comment]
It should not help. I had at least 10 MaxSealingSectorsForDeals but had the described troubles anyway.
But even if you set it to 1, shouldn't miner start sealing deals even with 1 allowed sector at a time?

**Comment by j1v** [comment]
@Shekelme I can confirm that raising MaxSealingSectorsForDeals and MaxWaitDealsSectors I no longer observe the issue

**Comment by Shekelme** [comment]
The issue is closed while the problem is not solved. I like PL.

**Comment by jennijuju** [comment]
> The issue is closed while the problem is not solved. I like PL.

Excuse me? The issue was closed b/c the author said the issue he/she reported was no longer observed after updating the right configuration.

**Comment by Shekelme** [comment]
Have you read my comments on this issue? Simply increasing these parameter (MaxSealingSectorsForDeals and MaxWaitDealsSectors) does not mean solving the problem. Yes, the problem has ceased to manifest itself, but the logic of the miner's work was vicious, so it remained vicious.
Please correct me if I'm wrong, but it still seems to me that even if you set these parameters to 1 or 2, shouldn't miner start sealing deals immideately, even with 1 or 2 allowed sectors with deals at a time?
I remind you that I was assigned a value of either 7 or 10, but in order to seal the sectors with deals, I had to wait for the end of the entire sealing of the CC sectors. Yes, well, let's increase the value. But this is not a solution, but just a workaround.
That's what I'm trying to convey to you.

**Comment by jennijuju** [comment]
> Have you read my comments on this issue? Simply increasing these parameter (MaxSealingSectorsForDeals and MaxWaitDealsSectors) does not mean solving the problem. Yes, the problem has ceased to manifest itself, but the logic of the miner's work was vicious, so it remained vicious.
> Please correct me if I'm wrong, but it still seems to me that even if you set these parameters to 1 or 2, shouldn't miner start sealing deals immideately, even with 1 or 2 allowed sectors with deals at a time?
> I remind you that I was assigned a value of either 7 or 10, but in order to seal the sectors with deals, I had to wait for the end of the entire sealing of the CC sectors. Yes, well, let's increase the value. But this is not a solution, but just a workaround.
> That's what I'm trying to convey to you.

This is fair - what you are describing is an improvement you’d like but not a bug of existing implementation.  let’s create an enhancement requirement  ticket and describe the solution you’d like, and we may get it looked at.

**Comment by Shekelme** [comment]
That is, the miner incorrectly processes the value from the config.toml (and you do not dispute this), but this is not a bug? I don't even know what to say.

**Comment by j1v** [comment]
I think @Shekelme is right - thist to mee looks like a bug, not a misconfiguration. I only said the solution from the other issue worked for me in order to give clues. 

To me this logic, if it's working as supposed is at least misleading and should be fixed

**Comment by jennijuju** [comment]
> That is, the miner incorrectly processes the value from the config.toml (and you do not dispute this), but this is not a bug? I don't even know what to say.

I obviously missed this part

**Comment by jennijuju** [comment]
@Shekelme @j1v thank you both for keeping bring the issue up until it gets properly noticed!

@magik6k 👁️ please?

**Comment by magik6k** [comment]
Part of the issue was likely fixed in  https://github.com/filecoin-project/lotus/pull/7256/files#diff-899955836c0e22bd6cb88bd54441aba07d7ffd85473afcf1171a88138652716fR117-R120, which is now in master

The other part might be that `MaxSealingSectorsForDeals` was equal or lower than `MaxWaitDealsSectors` - was that the case here?

**Comment by Shekelme** [comment]
Probably not. It is difficult to check in the absence of an active Slingstot phase...

**Comment by Shekelme** [comment]
I have just imported a few deals.
![image](https://user-images.githubusercontent.com/26449500/134414062-cea9aace-d75f-46e9-b96c-29e710195184.png)
My settings are
  ```
MaxWaitDealsSectors = 5
  MaxSealingSectors = 100
  MaxSealingSectorsForDeals = 20
  WaitDealsDelay = "1h0m0s"

```

**Comment by Shekelme** [comment]
The problem is still exist. v1.11.3
@j1v what are your values in [Sealing] section?

**Comment by NSC-FIL** [comment]
Using magikal branch (lotus-miner version 1.13.0-rc2+mainnet+git.82e1e474b) now. It seems prior to the magikal branch update, a WaitDeal sector with an 8GB verified deal failed and was removed after upgrading to v.1.13.0-rc2.  Then another deal with a 32GB verified deal was put into AP and failed, but a deal id was created but not included in the AP sector.  Then when I upgraded to the magikal branch, that AP sector is now in PC1 and sealing as a CC sector.  
The logs are here. Any questions can be directed to me on slack handle: Nelson 

https://drive.google.com/drive/folders/1K3jDckv6e2eMR4wSA6olTT84K5KVHDRG?usp=sharing

**Comment by jennijuju** [comment]
> Logs would be very helpful here

More can be found https://drive.google.com/drive/folders/1MlTbXLfhnKcQ6q4HuyD3R0UlcLztz3ZB

**Comment by Eliovp** [comment]
I can confirm this issue. 
Have to complete all CC sectors in order for the deals to start.

Strange logic :/
